/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/angular2-tinymce.component';
import * as i2 from '@angular/forms';
const styles_TinymceComponent:any[] = ([] as any[]);
export const RenderType_TinymceComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TinymceComponent,data:{}});
export function View_TinymceComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),
      [[8,'id',0]],(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (_ck,_v) => {
        var _co:i1.TinymceComponent = _v.component;
        const currVal_0:any = i0.ɵinlineInterpolate(1,'',_co.elementId,'');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_TinymceComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'app-tinymce',
      ([] as any[]),(null as any),(null as any),(null as any),View_TinymceComponent_0,
      RenderType_TinymceComponent)),i0.ɵprd(5120,(null as any),i2.NG_VALUE_ACCESSOR,
      (p0_0:any) => {
        return [p0_0];
      },[i1.TinymceComponent]),i0.ɵdid(4374528,(null as any),0,i1.TinymceComponent,
      [i0.NgZone,'TINYMCE_CONFIG'],(null as any),(null as any))],(null as any),(null as any));
}
export const TinymceComponentNgFactory:i0.ComponentFactory<i1.TinymceComponent> = i0.ɵccf('app-tinymce',
    i1.TinymceComponent,View_TinymceComponent_Host_0,{config:'config'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovUmVwc0dpdC9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9SZXBzR2l0L2FuZ3VsYXIyLXRpbnltY2Uvc3JjL2FuZ3VsYXIyLXRpbnltY2UuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovUmVwc0dpdC9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cy5UaW55bWNlQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9SZXBzR2l0L2FuZ3VsYXIyLXRpbnltY2Uvc3JjL2FuZ3VsYXIyLXRpbnltY2UuY29tcG9uZW50LnRzLlRpbnltY2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGlkPVwie3tlbGVtZW50SWR9fVwiPjwvZGl2PiIsIjxhcHAtdGlueW1jZT48L2FwcC10aW55bWNlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBOzs7UUFBSztRQUFMLFdBQUssU0FBTDs7OztvQkNBQTtNQUFBO2lDQUFBO01BQUE7UUFBQTtNQUFBLGdDQUFBO01BQUE7OzsifQ==
